# Generated by Django 3.0.5 on 2020-07-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=10)),
                ('jurisdiction', models.CharField(max_length=10)),
                ('entry_date', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('visits', models.CharField(max_length=10)),
                ('finally_log_ip', models.CharField(max_length=10)),
                ('finally_log_time', models.CharField(max_length=20)),
                ('qq', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
            ],
        ),
    ]
